#ifndef AMMUNITION_PSM__IDL
#define AMMUNITION_PSM__IDL

#include "LDM_Primitive_PSM.idl"
#include "LDM_Common_PSM.idl"
#include "LDM_Geometry_PSM.idl"
#include "LDM_Confidentiality_Label_PSM.idl"
#include "GVA_Common_PSM.idl"

@doc("Scope
    -   Tactical effectors that make use of ammunition
    Description
    This Domain describes properties of ammunition that are common to different types of weapon.
    Examples
    -   Automatic weapon
    -   Manual weapon
    Concept of operation
    This Domain does not model operation. It is used to provide a common definition of ammunition properties which are included by weapon systems defined in other domains. Its function is similar to a common header file in software.
    Use cases
    N/A
    Design Intent
    The Ammunition domain is only used in conjunction with weapon domains and forms part of the Tactical_Effectors composite domain.")
module P_Ammunition_PSM
{
   @doc("All GVA Resources shall publish a common cesponse topic for each Domain Module they implement. Each Response message published shall use the same value for referenceNum as the Command message it is responding to.")
   @mutable
   struct C_Ammunition_CommandResponse
   {
      @doc("The resourceID of the LRU which will receive the sample.")
      @hashid @key P_GVA_Common_PSM::T_IdentifierType A_recipientID;
      @doc("The resourceID of the LRU which publishes this sample.")
      @hashid @key P_GVA_Common_PSM::T_IdentifierType A_sourceID;
      @doc("Identifies a sample published on a command topic. Each commanding resoure is responsible for ensuring that it stamps each sample it publishes on a particular Command Topic with a unique Reference Number (e.g. through an incrementing counter). When a commanded Resource publishes a sample on Command Response Topic, it must set the Reference Number to the same value as the Command to which it is responding.")
      @hashid P_LDM_Primitive_PSM::T_Int64 A_referenceNum;
      @doc("Specifies the metadata for this sample.")
      @hashid P_GVA_Common_PSM::T_MetadataType A_metadata;
      @doc("Enumerated type with several common error codes defined. If an operation fails, Resources shall use the value that most closely reflects the underlying reason for the failure")
      @hashid P_GVA_Common_PSM::T_ResponseCodeType A_responseCode;
      @doc("LRU-specific error code to be used if an LRU gives an error response not covered by the standard GVA error codes. In the special case where  ResponseCodeAttributeType is L_ResponseCodeType_Pending, this attribute shall be set to the the worst-case time to completion in milliseconds.")
      @hashid P_LDM_Primitive_PSM::T_Int32 A_additionalResponseCode;
   };

   @doc("The nature of the ammunition.")
   @mutable
   struct C_Ammunition_Nature
   {
      @doc("The resourceID of the LRU which publishes this sample.")
      @hashid @key P_GVA_Common_PSM::T_IdentifierType A_sourceID;
      @doc("Specifies the metadata for this sample.")
      @hashid P_GVA_Common_PSM::T_MetadataType A_metadata;
      @doc("The total number of rounds of this ammunition nature available.")
      @hashid P_LDM_Primitive_PSM::T_Int32 A_storedRounds;
      @hashid P_GVA_Common_PSM::T_IdentifierType A_ammunitionNatureSpecification_sourceID;
   };

   @doc("Defines, via a set of attributes, the properties common to all natures of ammunition.")
   @mutable
   struct C_Ammunition_Nature_Specification
   {
      @doc("The resourceID of the LRU which publishes this sample.")
      @hashid @key P_GVA_Common_PSM::T_IdentifierType A_sourceID;
      @doc("Specifies the metadata for this sample.")
      @hashid P_GVA_Common_PSM::T_MetadataType A_metadata;
      @doc("A human readable identifier for the type name of the Ammunition. This shall be a text string in the following format as defined in the LDM Methodology and Modelling Standard:
          The uppercase labels that prefix each descriptor value are literal strings. Names in <angleBrackets> represent placeholders for actual values.
          TYPE_NAME::<typeName>
          <typeName> is generally an acronyms. Examples include:
          HESH
          APFSDS
          TP
          TPRR
          HEAT
          GPR
          GPR-AB")
      @hashid P_LDM_Common_PSM::T_DescriptorType A_ammunitionTypeName;
      @doc("A Boolean parameter which, when set to TRUE, indicates that airburst is available for this nature of ammunition.")
      @hashid P_LDM_Primitive_PSM::T_Boolean A_airburstAvailable;
      @doc("Indicates the calibre of this ammunition nature.")
      @hashid P_LDM_Common_PSM::T_WeaponAmmunitionCalibreType A_ammunitionCalibre;
   };
};

#endif
