#ifndef AUDIO_PSM__IDL
#define AUDIO_PSM__IDL

#include "Multimedia_Routing_PSM.idl"
#include "LDM_Primitive_PSM.idl"
#include "LDM_Common_PSM.idl"
#include "LDM_Geometry_PSM.idl"
#include "LDM_Confidentiality_Label_PSM.idl"
#include "GVA_Common_PSM.idl"

@doc("This package contains data types related to the audio domain.")
module P_Audio_PSM
{
   @doc("Specification values for the audio input detection mode. This is the mode by which a device will detect if an audio input signal has been received i.e. the trigger for onwards transmission.")
   @appendable
   enum T_InputDetectionModeType
   {
      L_InputDetectionMode__Invalid,
      @doc("audio input is always open.")
      L_InputDetectionMode__Continuous,
      @doc("audio input is triggered by a push to talk signal.")
      L_InputDetectionMode__PushToTalk,
      @doc("audio input is triggered if the device detects someone speaking.")
      L_InputDetectionMode__VoiceDetection
   };

   @doc("Describes the type of audio format.
       Note: Enumeration literals aligned with USB Audio v3.0.")
   @appendable
   enum T_AudioFormatType
   {
      L_AudioFormat__Invalid,
      L_AudioFormat__PCM,
      L_AudioFormat__PMC8,
      L_AudioFormat__IEEE_FLOAT,
      L_AudioFormat__ALAW,
      L_AudioFormat__MULAW,
      L_AudioFormat__DSD,
      L_AudioFormat__RAW_DATA,
      L_AudioFormat__PCM_IEC60958,
      L_AudioFormat__AC_3,
      L_AudioFormat__MPEG1_Layer1,
      L_AudioFormat__MPEG1_Layer2_3,
      L_AudioFormat__MPEG2_EXT,
      L_AudioFormat__MPEG2_ACC_ADTS,
      L_AudioFormat__MPEG2_Layer1_LS,
      L_AudioFormat__MPEG2_Layer2_3_LS,
      L_AudioFormat__DTS_I,
      L_AudioFormat__DTS_II,
      L_AudioFormat__DTS_III,
      L_AudioFormat__ATRAC,
      L_AudioFormat__ATRAC_2_3,
      L_AudioFormat__WMA,
      L_AudioFormat__E_AC_3,
      L_AudioFormat__MAT,
      L_AudioFormat__DTS_IV,
      L_AudioFormat__MPEG4_HE_AAC,
      L_AudioFormat__MPEG4_HE_AAC_V2,
      L_AudioFormat__MPEG4_AAC_LC,
      L_AudioFormat__DRA,
      L_AudioFormat__MPEG4_HE_AAC_SURROUND,
      L_AudioFormat__MPEG4_AAC_LC_SURROUND,
      L_AudioFormat__MPEG4_H_3D_AUDIO,
      L_AudioFormat__AC4,
      L_AudioFormat__MPEG4_AAC_ELD
   };

   @doc("Describes the compression algorithm used in an audio format.")
   @appendable
   enum T_AudioCompressionAlgorithmType
   {
      L_AudioCompressionAlgorithm__Invalid,
      L_AudioCompressionAlgorithm__LOSSLESS,
      L_AudioCompressionAlgorithm__ACELP,
      L_AudioCompressionAlgorithm__SPEECH,
      L_AudioCompressionAlgorithm__MDCT,
      L_AudioCompressionAlgorithm__VSELP,
      L_AudioCompressionAlgorithm__RPE_LTP,
      L_AudioCompressionAlgorithm__BI_LPC,
      L_AudioCompressionAlgorithm__SUBBAND,
      L_AudioCompressionAlgorithm__LPC,
      L_AudioCompressionAlgorithm__LTP,
      L_AudioCompressionAlgorithm__CELP,
      L_AudioCompressionAlgorithm__MLT,
      L_AudioCompressionAlgorithm__PCM,
      L_AudioCompressionAlgorithm__ADPCM,
      L_AudioCompressionAlgorithm__CS_CELP
   };

   @doc("Describes the type of audio resource or device.
       Note: Enumeration literals aligned with USB Audio v3.0.")
   @appendable
   enum T_AudioResourceType
   {
      L_AudioResource__Invalid,
      L_AudioResource__DeskSpeaker,
      L_AudioResource__Microphone,
      L_AudioResource__Headphone,
      L_AudioResource__Headset,
      L_AudioResource__Recorder,
      L_AudioResource__InputOutputBox,
      L_AudioResource__ControlPanel,
      L_AudioResource__Telephone,
      L_AudioResource__AudioVideo,
      L_AudioResource__Converter,
      L_AudioResource__Headset_Adapter,
      L_AudioResource__Speaker,
      L_AudioResource__SpeakerPhone,
      L_AudioResource__Other
   };

   @doc("The intent and purpose of the audio channel.
       Note: Enumeration literals aligned with USB Audio v3.0")
   @appendable
   enum T_AudioChannelPurposeType
   {
      L_AudioChannelPurpose__Invalid,
      @doc("contains audio primarily used for direct capture or reproduction.")
      L_AudioChannelPurpose__GenericAudio,
      @doc("intended to be interpreted by humans.")
      L_AudioChannelPurpose__Voice,
      @doc("intended to be interpreted or generated by machine.")
      L_AudioChannelPurpose__Speech,
      @doc("contains audio other than the primary channels.")
      L_AudioChannelPurpose__Ambient,
      @doc("contains final processed audio.")
      L_AudioChannelPurpose__Reference,
      @doc("contains signals with spectral content above audible limits (typically >20 kHz).")
      L_AudioChannelPurpose__Ultrasonic,
      @doc("contains very low frequency information, typically used to actuate vibrators or motion.")
      L_AudioChannelPurpose__VibroKinetic,
      @doc("indicates that the channel carries non-audio information. Examples of non-audio information.")
      L_AudioChannelPurpose__NonAudio
   };

   @doc("An enumerated value that describes the relationship of a channel with respect to other channels. It can be considered as the spatial location of the audio channel.
       Note: Enumeration literals aligned with USB Audio v3.0.")
   @appendable
   enum T_AudioChannelRelationshipType
   {
      L_AudioChannelRelationship__Invalid,
      L_AudioChannelRelationship__Mono,
      L_AudioChannelRelationship__Left,
      L_AudioChannelRelationship__Right,
      L_AudioChannelRelationship__Array,
      L_AudioChannelRelationship__FrontLeft,
      L_AudioChannelRelationship__FrontRight,
      L_AudioChannelRelationship__FrontCenter,
      L_AudioChannelRelationship__FrontLeftOfCenter,
      L_AudioChannelRelationship__FrontRightOfCenter,
      L_AudioChannelRelationship__FrontWideLeft,
      L_AudioChannelRelationship__FrontWideRight,
      L_AudioChannelRelationship__SideLeft,
      L_AudioChannelRelationship__SideRight,
      L_AudioChannelRelationship__SoundArrayLeft,
      L_AudioChannelRelationship__SoundArrayRight,
      L_AudioChannelRelationship__BackLeft,
      L_AudioChannelRelationship__BackRight,
      L_AudioChannelRelationship__BackCenter,
      L_AudioChannelRelationship__BackLeftOfCenter,
      L_AudioChannelRelationship__BackRightOfCenter,
      L_AudioChannelRelationship__BackWideLeft,
      L_AudioChannelRelationship__BackWideRight,
      L_AudioChannelRelationship__TopCenter,
      L_AudioChannelRelationship__TopFrontLeft,
      L_AudioChannelRelationship__TopFrontRight,
      L_AudioChannelRelationship__TopFrontCenter,
      L_AudioChannelRelationship__TopFrontLeftOfCenter,
      L_AudioChannelRelationship__TopFrontRightOfCenter,
      L_AudioChannelRelationship__TopFrontWideLeft,
      L_AudioChannelRelationship__TopFrontWideRight,
      L_AudioChannelRelationship__TopSoundArrayLeft,
      L_AudioChannelRelationship__TopSoundArrayRight,
      L_AudioChannelRelationship__TopBackLeft,
      L_AudioChannelRelationship__TopBackRight,
      L_AudioChannelRelationship__TopBackCenter,
      L_AudioChannelRelationship__TopBackLeftOfCenter,
      L_AudioChannelRelationship__TopBackRightOfCenter,
      L_AudioChannelRelationship__TopBackWideLeft,
      L_AudioChannelRelationship__TopBackWideRight,
      L_AudioChannelRelationship__BottomCenter,
      L_AudioChannelRelationship__BottomFrontLeft,
      L_AudioChannelRelationship__BottomFrontRight,
      L_AudioChannelRelationship__BottomFrontCenter,
      L_AudioChannelRelationship__BottomFrontLeftOfCenter,
      L_AudioChannelRelationship__BottomFrontRightOfCenter,
      L_AudioChannelRelationship__BottomFrontWideLeft,
      L_AudioChannelRelationship__BottomFrontWideRight,
      L_AudioChannelRelationship__BottomSideLeft,
      L_AudioChannelRelationship__BottomSideRight,
      L_AudioChannelRelationship__BottomSurroundArrayLeft,
      L_AudioChannelRelationship__BottomSurroundArrayRight,
      L_AudioChannelRelationship__BottomBackLeft,
      L_AudioChannelRelationship__BottomBackRight,
      L_AudioChannelRelationship__BottomBackCenter,
      L_AudioChannelRelationship__BottomBackLeftOfCenter,
      L_AudioChannelRelationship__BottomBackRightOfCenter,
      L_AudioChannelRelationship__BottomBackWideLeft,
      L_AudioChannelRelationship__BottomBackWideRight,
      L_AudioChannelRelationship__LowFrequencyEffects,
      L_AudioChannelRelationship__LowFrequencyEffectsLeft,
      L_AudioChannelRelationship__LowFrequencyEffectsRight,
      L_AudioChannelRelationship__HeadphoneLeft,
      L_AudioChannelRelationship__HeadphoneRight
   };

   @doc("The status of an audio activity such as recording and playback.")
   @appendable
   enum T_AudioActivityStatusType
   {
      L_AudioActivityStatus__Invalid,
      L_AudioActivityStatus__Inactive,
      L_AudioActivityStatus__Active,
      L_AudioActivityStatus__Paused
   };

   @doc("Describes the type of noise cancellation being used.")
   @appendable
   enum T_NoiseCancellationModeType
   {
      L_NoiseCancellationMode__Invalid,
      @doc("resource is not using noise cancelling.")
      L_NoiseCancellationMode__Off,
      @doc("resource is using active noise cancelling.")
      L_NoiseCancellationMode__Active,
      @doc("resource is using passive noise cancelling.")
      L_NoiseCancellationMode__Passive
   };

   @doc("Describes the details of an audio tag.")
   @mutable
   @nested
   struct T_AudioTagType
   {
      @doc("The name of the audio tag.")
      @hashid P_LDM_Common_PSM::T_DescriptorType A_tag;
      @doc("The value of the audio tag.")
      @hashid P_LDM_Primitive_PSM::T_MediumString A_value;
   };

   @doc("A list of audio tags.")
   typedef sequence <T_AudioTagType> T_AudioTagListType;

   @doc("Describes the transmission mode of the audio output e.g mono or stereo.")
   @appendable
   enum T_AudioTransmissionModeType
   {
      L_AudioTransmissionMode__Invalid,
      L_AudioTransmissionMode__Mono,
      L_AudioTransmissionMode__Stereo
   };

   @doc("A list of audio resource identifiers.")
   typedef sequence <P_GVA_Common_PSM::T_IdentifierType> T_AudioResourceListType;

   @doc("Describes the details of an audio group.")
   @mutable
   @nested
   struct T_AudioGroupType
   {
      @doc("The group identifier.")
      @hashid P_LDM_Primitive_PSM::T_Int16 A_groupId;
      @doc("The name of the group.")
      @hashid P_LDM_Common_PSM::T_DescriptorType A_groupName;
      @doc("The list of audio providers in the group.")
      @hashid T_AudioResourceListType A_providers;
      @doc("The list of audio receivers in the group.")
      @hashid T_AudioResourceListType A_receivers;
   };

   @doc("A list of audio transmission modes.")
   typedef sequence <T_AudioTransmissionModeType, 2> T_AudioTransmissionModeListType;

   @doc("A list of noise cancellation modes.")
   typedef sequence <T_NoiseCancellationModeType> T_NoiseCancellationModeListType;

   @doc("A list of named filter parameters.")
   typedef sequence <P_LDM_Primitive_PSM::T_MediumString> T_FilterParameterNameListType;

   @doc("Describes the details of an audio track.")
   @mutable
   @nested
   struct T_AudioTrackType
   {
      @doc("The unique identifier for the audio track.")
      @hashid P_LDM_Primitive_PSM::T_Int16 A_trackId;
      @doc("The name of the audio track.")
      @hashid P_LDM_Common_PSM::T_DescriptorType A_trackName;
      @doc("The total duration of the audio track.")
      @hashid P_LDM_Common_PSM::T_DurationType A_trackLength;
      @doc("A set of tags that provide additional detail about the audio track e.g. source, year etc. Tags are represented as a list of name value pairs.")
      @hashid T_AudioTagListType A_tags;
   };

   @doc("A list of audio tracks.")
   typedef sequence <T_AudioTrackType> T_AudioTrackListType;

   @doc("A list of audio channel identifiers.")
   typedef sequence <P_GVA_Common_PSM::T_IdentifierType> T_AudioChannelListType;

   @doc("A list of audio groups.")
   typedef sequence <T_AudioGroupType> T_AudioGroupListType;

   @doc("All GVA Resources shall publish a common cesponse topic for each Domain Module they implement. Each Response message published shall use the same value for referenceNum as the Command message it is responding to.")
   @mutable
   struct C_Audio_CommandResponse
   {
      @doc("The resourceID of the LRU which will receive the sample.")
      @hashid @key P_GVA_Common_PSM::T_IdentifierType A_recipientID;
      @doc("The resourceID of the LRU which publishes this sample.")
      @hashid @key P_GVA_Common_PSM::T_IdentifierType A_sourceID;
      @doc("Identifies a sample published on a command topic. Each commanding resoure is responsible for ensuring that it stamps each sample it publishes on a particular Command Topic with a unique Reference Number (e.g. through an incrementing counter). When a commanded Resource publishes a sample on Command Response Topic, it must set the Reference Number to the same value as the Command to which it is responding.")
      @hashid P_LDM_Primitive_PSM::T_Int64 A_referenceNum;
      @doc("Specifies the metadata for this sample.")
      @hashid P_GVA_Common_PSM::T_MetadataType A_metadata;
      @doc("Enumerated type with several common error codes defined. If an operation fails, Resources shall use the value that most closely reflects the underlying reason for the failure")
      @hashid P_GVA_Common_PSM::T_ResponseCodeType A_responseCode;
      @doc("LRU-specific error code to be used if an LRU gives an error response not covered by the standard GVA error codes. In the special case where  ResponseCodeAttributeType is L_ResponseCodeType_Pending, this attribute shall be set to the the worst-case time to completion in milliseconds.")
      @hashid P_LDM_Primitive_PSM::T_Int32 A_additionalResponseCode;
   };

   @doc("Specialisation of Multimedia_Routing::Routable_Channel_Specification for an Audio_Provider_Channel and Audio_Receiver_Channel.")
   @mutable
   struct C_Audio_Channel_Specification : P_Multimedia_Routing_PSM::C_Routable_Channel_Specification
   {
      @doc("The stream IP address.")
      @hashid @optional P_LDM_Common_PSM::T_IPv4AddressType A_streamIpAddress;
      @doc("The RTP port used to deliver audio over IP network.")
      @hashid @optional P_LDM_Primitive_PSM::T_Int16 A_rtpPort;
      @doc("The control IP address.")
      @hashid @optional P_LDM_Common_PSM::T_IPv4AddressType A_controlIpAddress;
      @doc("The security setting for the audio channel secure or insecure.")
      @hashid P_LDM_Primitive_PSM::T_Boolean A_secureChannel;
      @doc("The intent and purpose of the audio channel.")
      @hashid T_AudioChannelPurposeType A_purpose;
      @doc("Describes the relationship of this channel with respect to other channels. It can be considered as the spatial location of the audio channel.")
      @hashid T_AudioChannelRelationshipType A_relationship;
      @doc("Describes whether this audio channel supports 3-Dimensional audio.")
      @hashid P_LDM_Primitive_PSM::T_Boolean A_supports3dAudio;
   };

   @doc("Operation that mutes a specific channel that is being provided.")
   @mutable
   struct C_Audio_Provider_Channel_mute
   {
      @doc("The resourceID of the LRU which will receive the sample.")
      @hashid @key P_GVA_Common_PSM::T_IdentifierType A_recipientID;
      @doc("The resourceID of the LRU which publishes this sample.")
      @hashid @key P_GVA_Common_PSM::T_IdentifierType A_sourceID;
      @doc("Identifies a sample published on a command topic. Each commanding resoure is responsible for ensuring that it stamps each sample it publishes on a particular Command Topic with a unique Reference Number (e.g. through an incrementing counter). When a commanded Resource publishes a sample on Command Response Topic, it must set the Reference Number to the same value as the Command to which it is responding.")
      @hashid P_LDM_Primitive_PSM::T_Int64 A_referenceNum;
      @doc("Specifies the metadata for this sample.")
      @hashid P_GVA_Common_PSM::T_MetadataType A_metadata;
      @doc("Boolean indicating whether a response is required to this command. If TRUE, a response is not required. If FALSE, a response is required.")
      @hashid P_LDM_Primitive_PSM::T_Boolean A_responseNotRequired;
      @doc("The mute status to be applied to the provider channel. False = Unmute and True = Mute.")
      @hashid P_LDM_Primitive_PSM::T_Boolean A_mute;
   };

   @doc("Specialisation of Multimedia_Routing::Routable_Provider_Channel to specify Audio_Provider_Channel.")
   @mutable
   struct C_Audio_Provider_Channel : P_Multimedia_Routing_PSM::C_Routable_Provider_Channel
   {
      @doc("Describes whether the channel is currently muted or not.")
      @hashid P_LDM_Primitive_PSM::T_Boolean A_muted;
      @doc("The geographical location of the source of the audio. This is only set if the channel supports 3-D audio and the resource is able to determine the location.")
      @hashid @optional P_LDM_Common_PSM::T_Coordinate3DType A_sourceLocation;
   };

   @doc("Operation that sets the volume for a specific channel that is being received.")
   @mutable
   struct C_Audio_Receiver_Channel_setVolume
   {
      @doc("The resourceID of the LRU which will receive the sample.")
      @hashid @key P_GVA_Common_PSM::T_IdentifierType A_recipientID;
      @doc("The resourceID of the LRU which publishes this sample.")
      @hashid @key P_GVA_Common_PSM::T_IdentifierType A_sourceID;
      @doc("Identifies a sample published on a command topic. Each commanding resoure is responsible for ensuring that it stamps each sample it publishes on a particular Command Topic with a unique Reference Number (e.g. through an incrementing counter). When a commanded Resource publishes a sample on Command Response Topic, it must set the Reference Number to the same value as the Command to which it is responding.")
      @hashid P_LDM_Primitive_PSM::T_Int64 A_referenceNum;
      @doc("Specifies the metadata for this sample.")
      @hashid P_GVA_Common_PSM::T_MetadataType A_metadata;
      @doc("Boolean indicating whether a response is required to this command. If TRUE, a response is not required. If FALSE, a response is required.")
      @hashid P_LDM_Primitive_PSM::T_Boolean A_responseNotRequired;
      @doc("The channel volume level to be set, expressed as a percentage.")
      @hashid P_LDM_Common_PSM::T_PercentageType A_volume;
   };

   @doc("Operation that mutes a specific channel that is being received.")
   @mutable
   struct C_Audio_Receiver_Channel_mute
   {
      @doc("The resourceID of the LRU which will receive the sample.")
      @hashid @key P_GVA_Common_PSM::T_IdentifierType A_recipientID;
      @doc("The resourceID of the LRU which publishes this sample.")
      @hashid @key P_GVA_Common_PSM::T_IdentifierType A_sourceID;
      @doc("Identifies a sample published on a command topic. Each commanding resoure is responsible for ensuring that it stamps each sample it publishes on a particular Command Topic with a unique Reference Number (e.g. through an incrementing counter). When a commanded Resource publishes a sample on Command Response Topic, it must set the Reference Number to the same value as the Command to which it is responding.")
      @hashid P_LDM_Primitive_PSM::T_Int64 A_referenceNum;
      @doc("Specifies the metadata for this sample.")
      @hashid P_GVA_Common_PSM::T_MetadataType A_metadata;
      @doc("Boolean indicating whether a response is required to this command. If TRUE, a response is not required. If FALSE, a response is required.")
      @hashid P_LDM_Primitive_PSM::T_Boolean A_responseNotRequired;
      @doc("The mute status to be applied to the receiver channel. False = Unmute and True = Mute.")
      @hashid P_LDM_Primitive_PSM::T_Boolean A_mute;
   };

   @doc("Specialisation of Multimedia_Routing::Routable_Receiver_Channel to specify Audio_Receiver_Channel.")
   @mutable
   struct C_Audio_Receiver_Channel : P_Multimedia_Routing_PSM::C_Routable_Receiver_Channel
   {
      @doc("Describes whether the channel is currently muted or not.")
      @hashid P_LDM_Primitive_PSM::T_Boolean A_muted;
      @doc("Describes the volume level of the channel.")
      @hashid P_LDM_Common_PSM::T_PercentageType A_volume;
   };

   @doc("Specialisation of Multimedia_Routing::Routable_Format_Specification to specify Audio_Format_Specification.")
   @mutable
   struct C_Audio_Format_Specification : P_Multimedia_Routing_PSM::C_Routable_Format_Specification
   {
      @doc("The type of audio format.")
      @hashid T_AudioFormatType A_format;
      @doc("The number of audio bits per sample.")
      @hashid P_LDM_Primitive_PSM::T_Int16 A_bitDepth;
      @doc("The audio sampling rate used by the format. Rate is represented as a frequency.")
      @hashid P_LDM_Common_PSM::T_FrequencyInHertzType A_sampleRate;
      @doc("The mode of audio transmission that is supported by the format.")
      @hashid @optional T_AudioTransmissionModeType A_transmissionMode;
      @doc("The compression type used to compress the audio.")
      @hashid @optional T_AudioCompressionAlgorithmType A_compressionAlgorithm;
      @doc("Format has been encoded using a Constant Bit Rate.")
      @hashid P_LDM_Primitive_PSM::T_Boolean A_encodedConstantBitRate;
      @doc("Format has been encoded using a Variable Bit Rate.")
      @hashid P_LDM_Primitive_PSM::T_Boolean A_encodedVariableBitRate;
   };

   @doc("Operation to delete an audio group.")
   @mutable
   struct C_Audio_Group_Controlller_deleteAudioGroup
   {
      @doc("The resourceID of the LRU which will receive the sample.")
      @hashid @key P_GVA_Common_PSM::T_IdentifierType A_recipientID;
      @doc("The resourceID of the LRU which publishes this sample.")
      @hashid @key P_GVA_Common_PSM::T_IdentifierType A_sourceID;
      @doc("Identifies a sample published on a command topic. Each commanding resoure is responsible for ensuring that it stamps each sample it publishes on a particular Command Topic with a unique Reference Number (e.g. through an incrementing counter). When a commanded Resource publishes a sample on Command Response Topic, it must set the Reference Number to the same value as the Command to which it is responding.")
      @hashid P_LDM_Primitive_PSM::T_Int64 A_referenceNum;
      @doc("Specifies the metadata for this sample.")
      @hashid P_GVA_Common_PSM::T_MetadataType A_metadata;
      @doc("Boolean indicating whether a response is required to this command. If TRUE, a response is not required. If FALSE, a response is required.")
      @hashid P_LDM_Primitive_PSM::T_Boolean A_responseNotRequired;
      @doc("The identifier of the audio group to be deleted.")
      @hashid P_LDM_Primitive_PSM::T_Int16 A_groupId;
   };

   @doc("Operation to update an audio group.")
   @mutable
   struct C_Audio_Group_Controlller_updateAudioGroup
   {
      @doc("The resourceID of the LRU which will receive the sample.")
      @hashid @key P_GVA_Common_PSM::T_IdentifierType A_recipientID;
      @doc("The resourceID of the LRU which publishes this sample.")
      @hashid @key P_GVA_Common_PSM::T_IdentifierType A_sourceID;
      @doc("Identifies a sample published on a command topic. Each commanding resoure is responsible for ensuring that it stamps each sample it publishes on a particular Command Topic with a unique Reference Number (e.g. through an incrementing counter). When a commanded Resource publishes a sample on Command Response Topic, it must set the Reference Number to the same value as the Command to which it is responding.")
      @hashid P_LDM_Primitive_PSM::T_Int64 A_referenceNum;
      @doc("Specifies the metadata for this sample.")
      @hashid P_GVA_Common_PSM::T_MetadataType A_metadata;
      @doc("Boolean indicating whether a response is required to this command. If TRUE, a response is not required. If FALSE, a response is required.")
      @hashid P_LDM_Primitive_PSM::T_Boolean A_responseNotRequired;
      @doc("The audio group details to be used to update the audio group. The current details of the group will be completely replaced with the new details that is passed in. The groupId attribute will be used to identify which group is to be updated.")
      @hashid T_AudioGroupType A_groupDetails;
   };

   @doc("Operation to setup an audio group.")
   @mutable
   struct C_Audio_Group_Controlller_createAudioGroup
   {
      @doc("The resourceID of the LRU which will receive the sample.")
      @hashid @key P_GVA_Common_PSM::T_IdentifierType A_recipientID;
      @doc("The resourceID of the LRU which publishes this sample.")
      @hashid @key P_GVA_Common_PSM::T_IdentifierType A_sourceID;
      @doc("Identifies a sample published on a command topic. Each commanding resoure is responsible for ensuring that it stamps each sample it publishes on a particular Command Topic with a unique Reference Number (e.g. through an incrementing counter). When a commanded Resource publishes a sample on Command Response Topic, it must set the Reference Number to the same value as the Command to which it is responding.")
      @hashid P_LDM_Primitive_PSM::T_Int64 A_referenceNum;
      @doc("Specifies the metadata for this sample.")
      @hashid P_GVA_Common_PSM::T_MetadataType A_metadata;
      @doc("Boolean indicating whether a response is required to this command. If TRUE, a response is not required. If FALSE, a response is required.")
      @hashid P_LDM_Primitive_PSM::T_Boolean A_responseNotRequired;
      @doc("The name to be assigned to the newly created audio group.")
      @hashid P_LDM_Common_PSM::T_DescriptorType A_name;
      @doc("The list of audio providers to be associated with the audio group.")
      @hashid T_AudioResourceListType A_providers;
      @doc("The list of audio receivers to be associated with the audio group.")
      @hashid T_AudioResourceListType A_receivers;
   };

   @doc("Specialisation of Multimedia_Routing::Routable_Resource for an Audio_Group_Controlller. An Audio_Group_Controlller is responsible for managing audio groups.")
   @mutable
   struct C_Audio_Group_Controlller : P_Multimedia_Routing_PSM::C_Routable_Resource
   {
      @doc("The list of currently supported groups.")
      @hashid T_AudioGroupListType A_groups;
   };

   @doc("Operation that deletes the selected audio track.")
   @mutable
   struct C_Audio_Recorder_deleteRecording
   {
      @doc("The resourceID of the LRU which will receive the sample.")
      @hashid @key P_GVA_Common_PSM::T_IdentifierType A_recipientID;
      @doc("The resourceID of the LRU which publishes this sample.")
      @hashid @key P_GVA_Common_PSM::T_IdentifierType A_sourceID;
      @doc("Identifies a sample published on a command topic. Each commanding resoure is responsible for ensuring that it stamps each sample it publishes on a particular Command Topic with a unique Reference Number (e.g. through an incrementing counter). When a commanded Resource publishes a sample on Command Response Topic, it must set the Reference Number to the same value as the Command to which it is responding.")
      @hashid P_LDM_Primitive_PSM::T_Int64 A_referenceNum;
      @doc("Specifies the metadata for this sample.")
      @hashid P_GVA_Common_PSM::T_MetadataType A_metadata;
      @doc("Boolean indicating whether a response is required to this command. If TRUE, a response is not required. If FALSE, a response is required.")
      @hashid P_LDM_Primitive_PSM::T_Boolean A_responseNotRequired;
      @doc("The identifier of the audio recording that is to be deleted.")
      @hashid P_LDM_Primitive_PSM::T_Int16 A_trackId;
   };

   @doc("Operation that resumes the recording of an audio stream. The recording must be already paused for this to have any effect.")
   @mutable
   struct C_Audio_Recorder_resume
   {
      @doc("The resourceID of the LRU which will receive the sample.")
      @hashid @key P_GVA_Common_PSM::T_IdentifierType A_recipientID;
      @doc("The resourceID of the LRU which publishes this sample.")
      @hashid @key P_GVA_Common_PSM::T_IdentifierType A_sourceID;
      @doc("Identifies a sample published on a command topic. Each commanding resoure is responsible for ensuring that it stamps each sample it publishes on a particular Command Topic with a unique Reference Number (e.g. through an incrementing counter). When a commanded Resource publishes a sample on Command Response Topic, it must set the Reference Number to the same value as the Command to which it is responding.")
      @hashid P_LDM_Primitive_PSM::T_Int64 A_referenceNum;
      @doc("Specifies the metadata for this sample.")
      @hashid P_GVA_Common_PSM::T_MetadataType A_metadata;
      @doc("Boolean indicating whether a response is required to this command. If TRUE, a response is not required. If FALSE, a response is required.")
      @hashid P_LDM_Primitive_PSM::T_Boolean A_responseNotRequired;
   };

   @doc("Operation that pauses the recording of an audio stream.")
   @mutable
   struct C_Audio_Recorder_pause
   {
      @doc("The resourceID of the LRU which will receive the sample.")
      @hashid @key P_GVA_Common_PSM::T_IdentifierType A_recipientID;
      @doc("The resourceID of the LRU which publishes this sample.")
      @hashid @key P_GVA_Common_PSM::T_IdentifierType A_sourceID;
      @doc("Identifies a sample published on a command topic. Each commanding resoure is responsible for ensuring that it stamps each sample it publishes on a particular Command Topic with a unique Reference Number (e.g. through an incrementing counter). When a commanded Resource publishes a sample on Command Response Topic, it must set the Reference Number to the same value as the Command to which it is responding.")
      @hashid P_LDM_Primitive_PSM::T_Int64 A_referenceNum;
      @doc("Specifies the metadata for this sample.")
      @hashid P_GVA_Common_PSM::T_MetadataType A_metadata;
      @doc("Boolean indicating whether a response is required to this command. If TRUE, a response is not required. If FALSE, a response is required.")
      @hashid P_LDM_Primitive_PSM::T_Boolean A_responseNotRequired;
   };

   @doc("Operation to stop recording the audio stream.")
   @mutable
   struct C_Audio_Recorder_stop
   {
      @doc("The resourceID of the LRU which will receive the sample.")
      @hashid @key P_GVA_Common_PSM::T_IdentifierType A_recipientID;
      @doc("The resourceID of the LRU which publishes this sample.")
      @hashid @key P_GVA_Common_PSM::T_IdentifierType A_sourceID;
      @doc("Identifies a sample published on a command topic. Each commanding resoure is responsible for ensuring that it stamps each sample it publishes on a particular Command Topic with a unique Reference Number (e.g. through an incrementing counter). When a commanded Resource publishes a sample on Command Response Topic, it must set the Reference Number to the same value as the Command to which it is responding.")
      @hashid P_LDM_Primitive_PSM::T_Int64 A_referenceNum;
      @doc("Specifies the metadata for this sample.")
      @hashid P_GVA_Common_PSM::T_MetadataType A_metadata;
      @doc("Boolean indicating whether a response is required to this command. If TRUE, a response is not required. If FALSE, a response is required.")
      @hashid P_LDM_Primitive_PSM::T_Boolean A_responseNotRequired;
   };

   @doc("Operation to starts the recording of an audio stream.")
   @mutable
   struct C_Audio_Recorder_record
   {
      @doc("The resourceID of the LRU which will receive the sample.")
      @hashid @key P_GVA_Common_PSM::T_IdentifierType A_recipientID;
      @doc("The resourceID of the LRU which publishes this sample.")
      @hashid @key P_GVA_Common_PSM::T_IdentifierType A_sourceID;
      @doc("Identifies a sample published on a command topic. Each commanding resoure is responsible for ensuring that it stamps each sample it publishes on a particular Command Topic with a unique Reference Number (e.g. through an incrementing counter). When a commanded Resource publishes a sample on Command Response Topic, it must set the Reference Number to the same value as the Command to which it is responding.")
      @hashid P_LDM_Primitive_PSM::T_Int64 A_referenceNum;
      @doc("Specifies the metadata for this sample.")
      @hashid P_GVA_Common_PSM::T_MetadataType A_metadata;
      @doc("Boolean indicating whether a response is required to this command. If TRUE, a response is not required. If FALSE, a response is required.")
      @hashid P_LDM_Primitive_PSM::T_Boolean A_responseNotRequired;
      @doc("The name to be assigned to the audio recording.")
      @hashid P_LDM_Common_PSM::T_DescriptorType A_trackName;
      @doc("The list of tags and their values to be associated with the recording.")
      @hashid T_AudioTagListType A_tags;
   };

   @doc("Specialisation of Multimedia_Routing::Routable_Receiver to specify Audio_Receiver.")
   @mutable
   struct C_Audio_Receiver : P_Multimedia_Routing_PSM::C_Routable_Receiver
   {
      @doc("The current audio filter settings.")
      @hashid @optional P_LDM_Common_PSM::T_NameValuePairListType A_filterParameters;
      @doc("The currently selected noise cancellation mode.")
      @hashid @optional T_NoiseCancellationModeType A_noiseCancellation;
      @doc("Describes the master volume level.")
      @hashid @optional P_LDM_Common_PSM::T_PercentageType A_masterVolume;
      @hashid P_GVA_Common_PSM::T_IdentifierType A_audioReceiverSpecification_sourceID;
   };

   @doc("Operation to set the transmission mode.")
   @mutable
   struct C_Audio_Provider_setTransmissionMode
   {
      @doc("The resourceID of the LRU which will receive the sample.")
      @hashid @key P_GVA_Common_PSM::T_IdentifierType A_recipientID;
      @doc("The resourceID of the LRU which publishes this sample.")
      @hashid @key P_GVA_Common_PSM::T_IdentifierType A_sourceID;
      @doc("Identifies a sample published on a command topic. Each commanding resoure is responsible for ensuring that it stamps each sample it publishes on a particular Command Topic with a unique Reference Number (e.g. through an incrementing counter). When a commanded Resource publishes a sample on Command Response Topic, it must set the Reference Number to the same value as the Command to which it is responding.")
      @hashid P_LDM_Primitive_PSM::T_Int64 A_referenceNum;
      @doc("Specifies the metadata for this sample.")
      @hashid P_GVA_Common_PSM::T_MetadataType A_metadata;
      @doc("Boolean indicating whether a response is required to this command. If TRUE, a response is not required. If FALSE, a response is required.")
      @hashid P_LDM_Primitive_PSM::T_Boolean A_responseNotRequired;
      @doc("The transmission mode to be used.")
      @hashid T_AudioTransmissionModeType A_mode;
   };

   @doc("Operation to enable or disable auto gain control.")
   @mutable
   struct C_Audio_Provider_setAutoGainControl
   {
      @doc("The resourceID of the LRU which will receive the sample.")
      @hashid @key P_GVA_Common_PSM::T_IdentifierType A_recipientID;
      @doc("The resourceID of the LRU which publishes this sample.")
      @hashid @key P_GVA_Common_PSM::T_IdentifierType A_sourceID;
      @doc("Identifies a sample published on a command topic. Each commanding resoure is responsible for ensuring that it stamps each sample it publishes on a particular Command Topic with a unique Reference Number (e.g. through an incrementing counter). When a commanded Resource publishes a sample on Command Response Topic, it must set the Reference Number to the same value as the Command to which it is responding.")
      @hashid P_LDM_Primitive_PSM::T_Int64 A_referenceNum;
      @doc("Specifies the metadata for this sample.")
      @hashid P_GVA_Common_PSM::T_MetadataType A_metadata;
      @doc("Boolean indicating whether a response is required to this command. If TRUE, a response is not required. If FALSE, a response is required.")
      @hashid P_LDM_Primitive_PSM::T_Boolean A_responseNotRequired;
      @doc("The status of the auto gain control functionality. False = Disabled and True = Enabled.")
      @hashid P_LDM_Primitive_PSM::T_Boolean A_enabled;
   };

   @doc("Operation to enable or disable echo cancellation.")
   @mutable
   struct C_Audio_Provider_setEchoCancellation
   {
      @doc("The resourceID of the LRU which will receive the sample.")
      @hashid @key P_GVA_Common_PSM::T_IdentifierType A_recipientID;
      @doc("The resourceID of the LRU which publishes this sample.")
      @hashid @key P_GVA_Common_PSM::T_IdentifierType A_sourceID;
      @doc("Identifies a sample published on a command topic. Each commanding resoure is responsible for ensuring that it stamps each sample it publishes on a particular Command Topic with a unique Reference Number (e.g. through an incrementing counter). When a commanded Resource publishes a sample on Command Response Topic, it must set the Reference Number to the same value as the Command to which it is responding.")
      @hashid P_LDM_Primitive_PSM::T_Int64 A_referenceNum;
      @doc("Specifies the metadata for this sample.")
      @hashid P_GVA_Common_PSM::T_MetadataType A_metadata;
      @doc("Boolean indicating whether a response is required to this command. If TRUE, a response is not required. If FALSE, a response is required.")
      @hashid P_LDM_Primitive_PSM::T_Boolean A_responseNotRequired;
      @doc("The status of echo cancellation functionality. False = Disabled and True = Enabled.")
      @hashid P_LDM_Primitive_PSM::T_Boolean A_enabled;
   };

   @doc("Operation to enable or disable noise suppression.")
   @mutable
   struct C_Audio_Provider_setNoiseSuppression
   {
      @doc("The resourceID of the LRU which will receive the sample.")
      @hashid @key P_GVA_Common_PSM::T_IdentifierType A_recipientID;
      @doc("The resourceID of the LRU which publishes this sample.")
      @hashid @key P_GVA_Common_PSM::T_IdentifierType A_sourceID;
      @doc("Identifies a sample published on a command topic. Each commanding resoure is responsible for ensuring that it stamps each sample it publishes on a particular Command Topic with a unique Reference Number (e.g. through an incrementing counter). When a commanded Resource publishes a sample on Command Response Topic, it must set the Reference Number to the same value as the Command to which it is responding.")
      @hashid P_LDM_Primitive_PSM::T_Int64 A_referenceNum;
      @doc("Specifies the metadata for this sample.")
      @hashid P_GVA_Common_PSM::T_MetadataType A_metadata;
      @doc("Boolean indicating whether a response is required to this command. If TRUE, a response is not required. If FALSE, a response is required.")
      @hashid P_LDM_Primitive_PSM::T_Boolean A_responseNotRequired;
      @doc("The status of the noise suppresion functionality. False = Disabled and True = Enabled.")
      @hashid P_LDM_Primitive_PSM::T_Boolean A_enabled;
   };

   @doc("Operation that mutes all the channels being provided. Effectively disabling any audio output.")
   @mutable
   struct C_Audio_Provider_muteAllChannels
   {
      @doc("The resourceID of the LRU which will receive the sample.")
      @hashid @key P_GVA_Common_PSM::T_IdentifierType A_recipientID;
      @doc("The resourceID of the LRU which publishes this sample.")
      @hashid @key P_GVA_Common_PSM::T_IdentifierType A_sourceID;
      @doc("Identifies a sample published on a command topic. Each commanding resoure is responsible for ensuring that it stamps each sample it publishes on a particular Command Topic with a unique Reference Number (e.g. through an incrementing counter). When a commanded Resource publishes a sample on Command Response Topic, it must set the Reference Number to the same value as the Command to which it is responding.")
      @hashid P_LDM_Primitive_PSM::T_Int64 A_referenceNum;
      @doc("Specifies the metadata for this sample.")
      @hashid P_GVA_Common_PSM::T_MetadataType A_metadata;
      @doc("Boolean indicating whether a response is required to this command. If TRUE, a response is not required. If FALSE, a response is required.")
      @hashid P_LDM_Primitive_PSM::T_Boolean A_responseNotRequired;
      @doc("The mute status to be applied to all provider channels. False = Unmute and True = Mute.")
      @hashid P_LDM_Primitive_PSM::T_Boolean A_mute;
   };

   @doc("Operation to set the input detection mode.")
   @mutable
   struct C_Audio_Provider_setInputDetectionMode
   {
      @doc("The resourceID of the LRU which will receive the sample.")
      @hashid @key P_GVA_Common_PSM::T_IdentifierType A_recipientID;
      @doc("The resourceID of the LRU which publishes this sample.")
      @hashid @key P_GVA_Common_PSM::T_IdentifierType A_sourceID;
      @doc("Identifies a sample published on a command topic. Each commanding resoure is responsible for ensuring that it stamps each sample it publishes on a particular Command Topic with a unique Reference Number (e.g. through an incrementing counter). When a commanded Resource publishes a sample on Command Response Topic, it must set the Reference Number to the same value as the Command to which it is responding.")
      @hashid P_LDM_Primitive_PSM::T_Int64 A_referenceNum;
      @doc("Specifies the metadata for this sample.")
      @hashid P_GVA_Common_PSM::T_MetadataType A_metadata;
      @doc("Boolean indicating whether a response is required to this command. If TRUE, a response is not required. If FALSE, a response is required.")
      @hashid P_LDM_Primitive_PSM::T_Boolean A_responseNotRequired;
      @doc("The input detection mode to be used.")
      @hashid T_InputDetectionModeType A_mode;
   };

   @doc("Specialisation of Multimedia_Routing::Routable_Provider to specify Audio_Provider.")
   @mutable
   struct C_Audio_Provider : P_Multimedia_Routing_PSM::C_Routable_Provider
   {
      @doc("The current input detection mode that is being used.")
      @hashid @optional T_InputDetectionModeType A_inputDetectionMode;
      @doc("Identifies if noise suppression is currently enabled or disabled.")
      @hashid @optional P_LDM_Primitive_PSM::T_Boolean A_noiseSuppression;
      @doc("Identifies if auto gain control is currently enabled or disabled.")
      @hashid @optional P_LDM_Primitive_PSM::T_Boolean A_autoGainControl;
      @doc("Identifies if echo cancellation is currently enabled or disabled.")
      @hashid @optional P_LDM_Primitive_PSM::T_Boolean A_echoCancellation;
      @doc("The current audio transmission mode that is being used.")
      @hashid @optional T_AudioTransmissionModeType A_transmissionMode;
      @hashid P_GVA_Common_PSM::T_IdentifierType A_audioProviderSpecification_sourceID;
   };

   @doc("Operation to set audio filter parameters.")
   @mutable
   struct C_Audio_Receiver_setFilterParameters
   {
      @doc("The resourceID of the LRU which will receive the sample.")
      @hashid @key P_GVA_Common_PSM::T_IdentifierType A_recipientID;
      @doc("The resourceID of the LRU which publishes this sample.")
      @hashid @key P_GVA_Common_PSM::T_IdentifierType A_sourceID;
      @doc("Identifies a sample published on a command topic. Each commanding resoure is responsible for ensuring that it stamps each sample it publishes on a particular Command Topic with a unique Reference Number (e.g. through an incrementing counter). When a commanded Resource publishes a sample on Command Response Topic, it must set the Reference Number to the same value as the Command to which it is responding.")
      @hashid P_LDM_Primitive_PSM::T_Int64 A_referenceNum;
      @doc("Specifies the metadata for this sample.")
      @hashid P_GVA_Common_PSM::T_MetadataType A_metadata;
      @doc("Boolean indicating whether a response is required to this command. If TRUE, a response is not required. If FALSE, a response is required.")
      @hashid P_LDM_Primitive_PSM::T_Boolean A_responseNotRequired;
      @doc("A list of the named filter parameters and values that are required to be set.")
      @hashid P_LDM_Common_PSM::T_NameValuePairListType A_parameters;
   };

   @doc("Operation to set the noise cancellation mode.")
   @mutable
   struct C_Audio_Receiver_setNoiseCancellationMode
   {
      @doc("The resourceID of the LRU which will receive the sample.")
      @hashid @key P_GVA_Common_PSM::T_IdentifierType A_recipientID;
      @doc("The resourceID of the LRU which publishes this sample.")
      @hashid @key P_GVA_Common_PSM::T_IdentifierType A_sourceID;
      @doc("Identifies a sample published on a command topic. Each commanding resoure is responsible for ensuring that it stamps each sample it publishes on a particular Command Topic with a unique Reference Number (e.g. through an incrementing counter). When a commanded Resource publishes a sample on Command Response Topic, it must set the Reference Number to the same value as the Command to which it is responding.")
      @hashid P_LDM_Primitive_PSM::T_Int64 A_referenceNum;
      @doc("Specifies the metadata for this sample.")
      @hashid P_GVA_Common_PSM::T_MetadataType A_metadata;
      @doc("Boolean indicating whether a response is required to this command. If TRUE, a response is not required. If FALSE, a response is required.")
      @hashid P_LDM_Primitive_PSM::T_Boolean A_responseNotRequired;
      @doc("The noise cancellation mode to be used.")
      @hashid T_NoiseCancellationModeType A_mode;
   };

   @doc("Operation that mutes all the channels being received. Effectively disabling any audio output, if the resource is an output device.")
   @mutable
   struct C_Audio_Receiver_muteAllChannels
   {
      @doc("The resourceID of the LRU which will receive the sample.")
      @hashid @key P_GVA_Common_PSM::T_IdentifierType A_recipientID;
      @doc("The resourceID of the LRU which publishes this sample.")
      @hashid @key P_GVA_Common_PSM::T_IdentifierType A_sourceID;
      @doc("Identifies a sample published on a command topic. Each commanding resoure is responsible for ensuring that it stamps each sample it publishes on a particular Command Topic with a unique Reference Number (e.g. through an incrementing counter). When a commanded Resource publishes a sample on Command Response Topic, it must set the Reference Number to the same value as the Command to which it is responding.")
      @hashid P_LDM_Primitive_PSM::T_Int64 A_referenceNum;
      @doc("Specifies the metadata for this sample.")
      @hashid P_GVA_Common_PSM::T_MetadataType A_metadata;
      @doc("Boolean indicating whether a response is required to this command. If TRUE, a response is not required. If FALSE, a response is required.")
      @hashid P_LDM_Primitive_PSM::T_Boolean A_responseNotRequired;
      @doc("The mute status to be applied to all receiver channels. False = Unmute and True = Mute.")
      @hashid P_LDM_Primitive_PSM::T_Boolean A_mute;
   };

   @doc("Operation that sets the output volume across all channels that are being received.")
   @mutable
   struct C_Audio_Receiver_setMasterVolume
   {
      @doc("The resourceID of the LRU which will receive the sample.")
      @hashid @key P_GVA_Common_PSM::T_IdentifierType A_recipientID;
      @doc("The resourceID of the LRU which publishes this sample.")
      @hashid @key P_GVA_Common_PSM::T_IdentifierType A_sourceID;
      @doc("Identifies a sample published on a command topic. Each commanding resoure is responsible for ensuring that it stamps each sample it publishes on a particular Command Topic with a unique Reference Number (e.g. through an incrementing counter). When a commanded Resource publishes a sample on Command Response Topic, it must set the Reference Number to the same value as the Command to which it is responding.")
      @hashid P_LDM_Primitive_PSM::T_Int64 A_referenceNum;
      @doc("Specifies the metadata for this sample.")
      @hashid P_GVA_Common_PSM::T_MetadataType A_metadata;
      @doc("Boolean indicating whether a response is required to this command. If TRUE, a response is not required. If FALSE, a response is required.")
      @hashid P_LDM_Primitive_PSM::T_Boolean A_responseNotRequired;
      @doc("The master volume level to be set, expressed as a percentage.")
      @hashid P_LDM_Common_PSM::T_PercentageType A_volume;
   };

   @doc("A specialist Audio_Receiver that is capable of recording audio.")
   @mutable
   struct C_Audio_Recorder : C_Audio_Receiver
   {
      @doc("The current status of the recording.")
      @hashid T_AudioActivityStatusType A_recordingStatus;
      @doc("The list of available audio tracks that have been recorded.")
      @hashid T_AudioTrackListType A_availableRecordings;
      @hashid P_GVA_Common_PSM::T_IdentifierType A_audioRecorderSpecification_sourceID;
   };

   @doc("Operation that turns off the mixing of the audio inputs. This will have the effect of disabling the audio output from the mixer.")
   @mutable
   struct C_Audio_Mixer_stopMixing
   {
      @doc("The resourceID of the LRU which will receive the sample.")
      @hashid @key P_GVA_Common_PSM::T_IdentifierType A_recipientID;
      @doc("The resourceID of the LRU which publishes this sample.")
      @hashid @key P_GVA_Common_PSM::T_IdentifierType A_sourceID;
      @doc("Identifies a sample published on a command topic. Each commanding resoure is responsible for ensuring that it stamps each sample it publishes on a particular Command Topic with a unique Reference Number (e.g. through an incrementing counter). When a commanded Resource publishes a sample on Command Response Topic, it must set the Reference Number to the same value as the Command to which it is responding.")
      @hashid P_LDM_Primitive_PSM::T_Int64 A_referenceNum;
      @doc("Specifies the metadata for this sample.")
      @hashid P_GVA_Common_PSM::T_MetadataType A_metadata;
      @doc("Boolean indicating whether a response is required to this command. If TRUE, a response is not required. If FALSE, a response is required.")
      @hashid P_LDM_Primitive_PSM::T_Boolean A_responseNotRequired;
   };

   @doc("Operation to select audio inputs that are to be combined into the audio output stream(s).")
   @mutable
   struct C_Audio_Mixer_configureChannels
   {
      @doc("The resourceID of the LRU which will receive the sample.")
      @hashid @key P_GVA_Common_PSM::T_IdentifierType A_recipientID;
      @doc("The resourceID of the LRU which publishes this sample.")
      @hashid @key P_GVA_Common_PSM::T_IdentifierType A_sourceID;
      @doc("Identifies a sample published on a command topic. Each commanding resoure is responsible for ensuring that it stamps each sample it publishes on a particular Command Topic with a unique Reference Number (e.g. through an incrementing counter). When a commanded Resource publishes a sample on Command Response Topic, it must set the Reference Number to the same value as the Command to which it is responding.")
      @hashid P_LDM_Primitive_PSM::T_Int64 A_referenceNum;
      @doc("Specifies the metadata for this sample.")
      @hashid P_GVA_Common_PSM::T_MetadataType A_metadata;
      @doc("Boolean indicating whether a response is required to this command. If TRUE, a response is not required. If FALSE, a response is required.")
      @hashid P_LDM_Primitive_PSM::T_Boolean A_responseNotRequired;
      @doc("A list of the audio receiver channels that will used as inputs into the mixer.")
      @hashid T_AudioChannelListType A_inputChannels;
      @doc("A list of the audio provider channels that will used as outputs from the mixer.")
      @hashid T_AudioChannelListType A_outputChannels;
   };

   @doc("Operation that turns on the mixing of the audio inputs. This will have the effect of enabling the audio output from the mixer.")
   @mutable
   struct C_Audio_Mixer_startMixing
   {
      @doc("The resourceID of the LRU which will receive the sample.")
      @hashid @key P_GVA_Common_PSM::T_IdentifierType A_recipientID;
      @doc("The resourceID of the LRU which publishes this sample.")
      @hashid @key P_GVA_Common_PSM::T_IdentifierType A_sourceID;
      @doc("Identifies a sample published on a command topic. Each commanding resoure is responsible for ensuring that it stamps each sample it publishes on a particular Command Topic with a unique Reference Number (e.g. through an incrementing counter). When a commanded Resource publishes a sample on Command Response Topic, it must set the Reference Number to the same value as the Command to which it is responding.")
      @hashid P_LDM_Primitive_PSM::T_Int64 A_referenceNum;
      @doc("Specifies the metadata for this sample.")
      @hashid P_GVA_Common_PSM::T_MetadataType A_metadata;
      @doc("Boolean indicating whether a response is required to this command. If TRUE, a response is not required. If FALSE, a response is required.")
      @hashid P_LDM_Primitive_PSM::T_Boolean A_responseNotRequired;
   };

   @doc("Specialisation of Multimedia_Routing::Composite_Routable_Resource to specify an Audio_Mixer. An Audio_Mixer combines a number of audio inputs into one or more audio outputs.
       Note: The mixing levels associated with each input channel into the mixer is controlled through each channel's associated Audio_Receiver.")
   @mutable
   struct C_Audio_Mixer : P_Multimedia_Routing_PSM::C_Composite_Routable_Resource
   {
      @doc("The list of channels being used by the mixer as input.")
      @hashid T_AudioChannelListType A_inputChannels;
      @doc("The list of channels being used by the mixer to output to.")
      @hashid T_AudioChannelListType A_outputChannels;
      @doc("The current status of the mixer.")
      @hashid T_AudioActivityStatusType A_mixerStatus;
   };

   @doc("Specialisation of Multimedia_Routing::Routable_Resource_Specification to specify Audio_Resource_Specification.")
   @mutable
   struct C_Audio_Resource_Specification : P_Multimedia_Routing_PSM::C_Routable_Resource_Specification
   {
      @doc("Identifies the type of audio resource.")
      @hashid T_AudioResourceType A_type;
      @hashid sequence <P_GVA_Common_PSM::T_IdentifierType> A_supportedAudioChannelSpecification_sourceID;
   };

   @doc("The specification of the audio channels that are supported by the audio resource.")
   @mutable
   struct C_Audio_Resource_Supported_Channel_Specification
   {
      @doc("The resourceID of the LRU which publishes this sample.")
      @hashid @key P_GVA_Common_PSM::T_IdentifierType A_sourceID;
      @doc("Specifies the metadata for this sample.")
      @hashid P_GVA_Common_PSM::T_MetadataType A_metadata;
      @doc("Descriptor for the supported channel that does not change during runtime.")
      @hashid P_LDM_Common_PSM::T_DescriptorType A_descriptor;
      @hashid P_GVA_Common_PSM::T_IdentifierType A_audioChannelSpecification_sourceID;
      @hashid P_GVA_Common_PSM::T_IdentifierType A_audioFormatSpecification_sourceID;
   };

   @doc("Operation that adjusts the speed at which an audio track will be played back. The audio player must support variable playback speeds, else this operation will return an error.")
   @mutable
   struct C_Audio_Player_setPlaybackSpeed
   {
      @doc("The resourceID of the LRU which will receive the sample.")
      @hashid @key P_GVA_Common_PSM::T_IdentifierType A_recipientID;
      @doc("The resourceID of the LRU which publishes this sample.")
      @hashid @key P_GVA_Common_PSM::T_IdentifierType A_sourceID;
      @doc("Identifies a sample published on a command topic. Each commanding resoure is responsible for ensuring that it stamps each sample it publishes on a particular Command Topic with a unique Reference Number (e.g. through an incrementing counter). When a commanded Resource publishes a sample on Command Response Topic, it must set the Reference Number to the same value as the Command to which it is responding.")
      @hashid P_LDM_Primitive_PSM::T_Int64 A_referenceNum;
      @doc("Specifies the metadata for this sample.")
      @hashid P_GVA_Common_PSM::T_MetadataType A_metadata;
      @doc("Boolean indicating whether a response is required to this command. If TRUE, a response is not required. If FALSE, a response is required.")
      @hashid P_LDM_Primitive_PSM::T_Boolean A_responseNotRequired;
      @doc("The speed multiplier to be used on playback e.g 0.5 = half speed and 2 = double speed.")
      @hashid P_LDM_Primitive_PSM::T_Double A_speed;
   };

   @doc("Operation that sets the current position of currently selected audio track. Represented as a duration from the start of the audio track.")
   @mutable
   struct C_Audio_Player_setTrackPosition
   {
      @doc("The resourceID of the LRU which will receive the sample.")
      @hashid @key P_GVA_Common_PSM::T_IdentifierType A_recipientID;
      @doc("The resourceID of the LRU which publishes this sample.")
      @hashid @key P_GVA_Common_PSM::T_IdentifierType A_sourceID;
      @doc("Identifies a sample published on a command topic. Each commanding resoure is responsible for ensuring that it stamps each sample it publishes on a particular Command Topic with a unique Reference Number (e.g. through an incrementing counter). When a commanded Resource publishes a sample on Command Response Topic, it must set the Reference Number to the same value as the Command to which it is responding.")
      @hashid P_LDM_Primitive_PSM::T_Int64 A_referenceNum;
      @doc("Specifies the metadata for this sample.")
      @hashid P_GVA_Common_PSM::T_MetadataType A_metadata;
      @doc("Boolean indicating whether a response is required to this command. If TRUE, a response is not required. If FALSE, a response is required.")
      @hashid P_LDM_Primitive_PSM::T_Boolean A_responseNotRequired;
      @doc("The position in time that the audio player is instructed to skip to.")
      @hashid P_LDM_Common_PSM::T_DurationType A_position;
   };

   @doc("Operation to select an audio track.")
   @mutable
   struct C_Audio_Player_selectTrack
   {
      @doc("The resourceID of the LRU which will receive the sample.")
      @hashid @key P_GVA_Common_PSM::T_IdentifierType A_recipientID;
      @doc("The resourceID of the LRU which publishes this sample.")
      @hashid @key P_GVA_Common_PSM::T_IdentifierType A_sourceID;
      @doc("Identifies a sample published on a command topic. Each commanding resoure is responsible for ensuring that it stamps each sample it publishes on a particular Command Topic with a unique Reference Number (e.g. through an incrementing counter). When a commanded Resource publishes a sample on Command Response Topic, it must set the Reference Number to the same value as the Command to which it is responding.")
      @hashid P_LDM_Primitive_PSM::T_Int64 A_referenceNum;
      @doc("Specifies the metadata for this sample.")
      @hashid P_GVA_Common_PSM::T_MetadataType A_metadata;
      @doc("Boolean indicating whether a response is required to this command. If TRUE, a response is not required. If FALSE, a response is required.")
      @hashid P_LDM_Primitive_PSM::T_Boolean A_responseNotRequired;
      @doc("The identifier of the audio track that is to be selected as the current track.")
      @hashid P_LDM_Primitive_PSM::T_Int16 A_trackId;
   };

   @doc("Operation that pauses the playing of the currently selected audio track.")
   @mutable
   struct C_Audio_Player_pause
   {
      @doc("The resourceID of the LRU which will receive the sample.")
      @hashid @key P_GVA_Common_PSM::T_IdentifierType A_recipientID;
      @doc("The resourceID of the LRU which publishes this sample.")
      @hashid @key P_GVA_Common_PSM::T_IdentifierType A_sourceID;
      @doc("Identifies a sample published on a command topic. Each commanding resoure is responsible for ensuring that it stamps each sample it publishes on a particular Command Topic with a unique Reference Number (e.g. through an incrementing counter). When a commanded Resource publishes a sample on Command Response Topic, it must set the Reference Number to the same value as the Command to which it is responding.")
      @hashid P_LDM_Primitive_PSM::T_Int64 A_referenceNum;
      @doc("Specifies the metadata for this sample.")
      @hashid P_GVA_Common_PSM::T_MetadataType A_metadata;
      @doc("Boolean indicating whether a response is required to this command. If TRUE, a response is not required. If FALSE, a response is required.")
      @hashid P_LDM_Primitive_PSM::T_Boolean A_responseNotRequired;
   };

   @doc("Operation that stops the playing of the currently selected audio track.")
   @mutable
   struct C_Audio_Player_stop
   {
      @doc("The resourceID of the LRU which will receive the sample.")
      @hashid @key P_GVA_Common_PSM::T_IdentifierType A_recipientID;
      @doc("The resourceID of the LRU which publishes this sample.")
      @hashid @key P_GVA_Common_PSM::T_IdentifierType A_sourceID;
      @doc("Identifies a sample published on a command topic. Each commanding resoure is responsible for ensuring that it stamps each sample it publishes on a particular Command Topic with a unique Reference Number (e.g. through an incrementing counter). When a commanded Resource publishes a sample on Command Response Topic, it must set the Reference Number to the same value as the Command to which it is responding.")
      @hashid P_LDM_Primitive_PSM::T_Int64 A_referenceNum;
      @doc("Specifies the metadata for this sample.")
      @hashid P_GVA_Common_PSM::T_MetadataType A_metadata;
      @doc("Boolean indicating whether a response is required to this command. If TRUE, a response is not required. If FALSE, a response is required.")
      @hashid P_LDM_Primitive_PSM::T_Boolean A_responseNotRequired;
   };

   @doc("Operation that plays the currently selected audio track. If audio track is paused, the audio track will resume play at the current position.")
   @mutable
   struct C_Audio_Player_play
   {
      @doc("The resourceID of the LRU which will receive the sample.")
      @hashid @key P_GVA_Common_PSM::T_IdentifierType A_recipientID;
      @doc("The resourceID of the LRU which publishes this sample.")
      @hashid @key P_GVA_Common_PSM::T_IdentifierType A_sourceID;
      @doc("Identifies a sample published on a command topic. Each commanding resoure is responsible for ensuring that it stamps each sample it publishes on a particular Command Topic with a unique Reference Number (e.g. through an incrementing counter). When a commanded Resource publishes a sample on Command Response Topic, it must set the Reference Number to the same value as the Command to which it is responding.")
      @hashid P_LDM_Primitive_PSM::T_Int64 A_referenceNum;
      @doc("Specifies the metadata for this sample.")
      @hashid P_GVA_Common_PSM::T_MetadataType A_metadata;
      @doc("Boolean indicating whether a response is required to this command. If TRUE, a response is not required. If FALSE, a response is required.")
      @hashid P_LDM_Primitive_PSM::T_Boolean A_responseNotRequired;
   };

   @doc("A specialist Audio_Provider that is capable of playing back recorded audio.")
   @mutable
   struct C_Audio_Player : C_Audio_Provider
   {
      @doc("The current status of the playback.")
      @hashid T_AudioActivityStatusType A_playbackStatus;
      @doc("The list of available audio tracks that can be played.")
      @hashid T_AudioTrackListType A_availableTracks;
      @doc("The identifier of the currently selected audio track. If no track is selected, then this should be set to zero.")
      @hashid P_LDM_Primitive_PSM::T_Int16 A_selectedTrack;
      @doc("The current position of the track that is being played. Represented as a duration from the start of the track.")
      @hashid P_LDM_Common_PSM::T_DurationType A_trackPosition;
      @doc("The current playback speed represented as a multiplier. By default this would be set to 1.0 i.e. normal speed.")
      @hashid P_LDM_Primitive_PSM::T_Double A_playbackSpeed;
      @hashid P_GVA_Common_PSM::T_IdentifierType A_audioPlayerSpecification_sourceID;
   };

   @doc("Operation to request to leave from an audio stream.")
   @mutable
   struct C_Audio_Channel_Controller_leaveAudioChannel
   {
      @doc("The resourceID of the LRU which will receive the sample.")
      @hashid @key P_GVA_Common_PSM::T_IdentifierType A_recipientID;
      @doc("The resourceID of the LRU which publishes this sample.")
      @hashid @key P_GVA_Common_PSM::T_IdentifierType A_sourceID;
      @doc("Identifies a sample published on a command topic. Each commanding resoure is responsible for ensuring that it stamps each sample it publishes on a particular Command Topic with a unique Reference Number (e.g. through an incrementing counter). When a commanded Resource publishes a sample on Command Response Topic, it must set the Reference Number to the same value as the Command to which it is responding.")
      @hashid P_LDM_Primitive_PSM::T_Int64 A_referenceNum;
      @doc("Specifies the metadata for this sample.")
      @hashid P_GVA_Common_PSM::T_MetadataType A_metadata;
      @doc("Boolean indicating whether a response is required to this command. If TRUE, a response is not required. If FALSE, a response is required.")
      @hashid P_LDM_Primitive_PSM::T_Boolean A_responseNotRequired;
      @doc("The identifier of the audio receiver wanting or being instructed to leave or stop receiving the audio channel.")
      @hashid P_GVA_Common_PSM::T_IdentifierType A_audioReceiver;
      @doc("The identifier of the audio channel that is required to be stopped from being received.")
      @hashid P_GVA_Common_PSM::T_IdentifierType A_providerChannel;
   };

   @doc("Operation to transfer audio stream from one AudioReceiver to another.")
   @mutable
   struct C_Audio_Channel_Controller_transferAudioChannel
   {
      @doc("The resourceID of the LRU which will receive the sample.")
      @hashid @key P_GVA_Common_PSM::T_IdentifierType A_recipientID;
      @doc("The resourceID of the LRU which publishes this sample.")
      @hashid @key P_GVA_Common_PSM::T_IdentifierType A_sourceID;
      @doc("Identifies a sample published on a command topic. Each commanding resoure is responsible for ensuring that it stamps each sample it publishes on a particular Command Topic with a unique Reference Number (e.g. through an incrementing counter). When a commanded Resource publishes a sample on Command Response Topic, it must set the Reference Number to the same value as the Command to which it is responding.")
      @hashid P_LDM_Primitive_PSM::T_Int64 A_referenceNum;
      @doc("Specifies the metadata for this sample.")
      @hashid P_GVA_Common_PSM::T_MetadataType A_metadata;
      @doc("Boolean indicating whether a response is required to this command. If TRUE, a response is not required. If FALSE, a response is required.")
      @hashid P_LDM_Primitive_PSM::T_Boolean A_responseNotRequired;
      @doc("The identifier of the audio receiver that is currently receiving the audio channel to be transferred.")
      @hashid P_GVA_Common_PSM::T_IdentifierType A_sourceAudioReceiver;
      @doc("The identifier of the audio provider channel that is being transferred.")
      @hashid P_GVA_Common_PSM::T_IdentifierType A_sourceProviderChannel;
      @doc("The identifier of the audio receiver that the audio channel is being requested to be transferred to.")
      @hashid P_GVA_Common_PSM::T_IdentifierType A_destinationAudioReceiver;
   };

   @doc("Operation to request to join an audio stream being streamed.")
   @mutable
   struct C_Audio_Channel_Controller_joinAudioChannel
   {
      @doc("The resourceID of the LRU which will receive the sample.")
      @hashid @key P_GVA_Common_PSM::T_IdentifierType A_recipientID;
      @doc("The resourceID of the LRU which publishes this sample.")
      @hashid @key P_GVA_Common_PSM::T_IdentifierType A_sourceID;
      @doc("Identifies a sample published on a command topic. Each commanding resoure is responsible for ensuring that it stamps each sample it publishes on a particular Command Topic with a unique Reference Number (e.g. through an incrementing counter). When a commanded Resource publishes a sample on Command Response Topic, it must set the Reference Number to the same value as the Command to which it is responding.")
      @hashid P_LDM_Primitive_PSM::T_Int64 A_referenceNum;
      @doc("Specifies the metadata for this sample.")
      @hashid P_GVA_Common_PSM::T_MetadataType A_metadata;
      @doc("Boolean indicating whether a response is required to this command. If TRUE, a response is not required. If FALSE, a response is required.")
      @hashid P_LDM_Primitive_PSM::T_Boolean A_responseNotRequired;
      @doc("The identifier of the audio receiver wanting or being instructed to join the audio channel.")
      @hashid P_GVA_Common_PSM::T_IdentifierType A_audioReceiver;
      @doc("The identifier of the audio channel that is being request to be joined.")
      @hashid P_GVA_Common_PSM::T_IdentifierType A_providerChannel;
   };

   @doc("Specialisation of Multimedia_Routing::Routable_Resource for an Audio_Channel_Controller. An Audio_Channel_Controller is responsible for co-ordinating access to and transfer of audio channels between Audio_Receivers.")
   @mutable
   struct C_Audio_Channel_Controller : P_Multimedia_Routing_PSM::C_Routable_Resource
   {
   };

   @doc("The specification for an audio provider.")
   @mutable
   struct C_Audio_Provider_Specification : C_Audio_Resource_Specification
   {
      @doc("Specifies whether auto gain control functionality is supported by the resource.")
      @hashid P_LDM_Primitive_PSM::T_Boolean A_autoGainControlSupported;
      @doc("Specifies whether echo cancellation functionality is supported by the resource.")
      @hashid P_LDM_Primitive_PSM::T_Boolean A_echoCancellationSupported;
      @doc("Specifies whether noise suppression functionality is supported by the resource.")
      @hashid P_LDM_Primitive_PSM::T_Boolean A_noiseSuppressionSupported;
      @doc("Specifies whether the resource supports the ability to mute all channels.")
      @hashid P_LDM_Primitive_PSM::T_Boolean A_muteAllChannelsSupported;
      @doc("The list of audio transmission modes supported by the resource.")
      @hashid T_AudioTransmissionModeListType A_supportedTransmissionModes;
      @doc("Specifies whether auto gain control can be enabled and disabled.")
      @hashid @optional P_LDM_Primitive_PSM::T_Boolean A_autoGainControlEnableDisable;
      @doc("Specifies whether echo cancellation can be enabled and disabled.")
      @hashid @optional P_LDM_Primitive_PSM::T_Boolean A_echoCancellationEnableDisable;
      @doc("Specifies whether noise suppression can be enabled and disabled.")
      @hashid @optional P_LDM_Primitive_PSM::T_Boolean A_noiseSuppresionEnableDisable;
   };

   @doc("The specification for an Audio_Receiver.")
   @mutable
   struct C_Audio_Receiver_Specification : C_Audio_Resource_Specification
   {
      @doc("Specifies whether the resource supports the ability to mute all channels.")
      @hashid P_LDM_Primitive_PSM::T_Boolean A_muteAllChannelsSupported;
      @doc("Specifies whether the resource supports a master volume control.")
      @hashid P_LDM_Primitive_PSM::T_Boolean A_masterVolumeSupported;
      @doc("The list of filter parameters supported by the resource.")
      @hashid T_FilterParameterNameListType A_supportedFilterParameters;
      @doc("The list of noise cancellation modes supported by the resource.")
      @hashid T_NoiseCancellationModeListType A_supportedNoiseCancellationModes;
   };

   @doc("The specification for an audio playback resource.")
   @mutable
   struct C_Audio_Player_Specification : C_Audio_Provider_Specification
   {
      @doc("Communicates if the player supports the ability to vary the speed at which audio tracks can be played back.")
      @hashid P_LDM_Primitive_PSM::T_Boolean A_setPlaybackSpeedSupported;
      @doc("If the player supports the ability to vary the playback speed, this represents the maximum speed multiplier that can be used e.g. 5.00 would represent x5 times.")
      @hashid @optional P_LDM_Primitive_PSM::T_Double A_maximumPlaybackSpeed;
      @doc("If the player supports the ability to vary the playback speed, this represents the minimum speed multiplier that can be used e.g. 0.1 would represent x0.1 times.")
      @hashid @optional P_LDM_Primitive_PSM::T_Double A_minimumPlaybackSpeed;
      @doc("If the player supports the ability to vary the playback speed, this represents the speed increments supported e.g. if the player supports speed increments of 0.25, and a minimum and maximum speed of 0 and 2 respectively, the following discrete playback speeds would be available for selection, 0.25, 0.5, 0.75, 1.0, 1.25, 1.5, 1.75, 2.0.")
      @hashid @optional P_LDM_Primitive_PSM::T_Double A_playackSpeedIncrement;
   };

   @doc("The specification for an audio recording resource.")
   @mutable
   struct C_Audio_Recorder_Specification : C_Audio_Receiver_Specification
   {
      @doc("The maximum duration for an individual recording.")
      @hashid @optional P_LDM_Common_PSM::T_DurationType A_recordingDurationLimit;
   };
};

#endif
