#ifndef LASER_WARNING_SYSTEM_PSM__IDL
#define LASER_WARNING_SYSTEM_PSM__IDL

#include "LDM_Primitive_PSM.idl"
#include "LDM_Common_PSM.idl"
#include "LDM_Geometry_PSM.idl"
#include "LDM_Confidentiality_Label_PSM.idl"
#include "GVA_Common_PSM.idl"
#include "Tactical_Sensor_PSM.idl"

@doc("This package defines
    - data produced by laser warning systems and intended to be shared with other subsystems,
    - commands exposed by laser warning systems and expected to be called by other subsystems.")
module P_Laser_Warning_System_PSM
{
   @doc("This identifies the different states of the life cycle of a laser detection.")
   @appendable
   enum T_Laser_Detection_StateType
   {
      L_LaserDetectionState__Invalid,
      @doc("This is the initial state of a laser detection, when illumination has been detected, but the type of illuminator is not known yet.")
      L_LaserDetectionState__Unclassified,
      @doc("The detection is in this state when the type of the illuminator has been identified or after a time-out when the detector will not be able to classify the detection.")
      L_LaserDetectionState__Classified,
      @doc("The detection is in this state when the detector is no longer illuminated.
          The detection can then be deleted by the detector.")
      L_LaserDetectionState__Finalised,
      @doc("The terminal state.")
      L_LaserDetectionState__LaserDetectionTerminationState
   };

   @doc("An enumerated set of possible classifications of a laser detection.
       When no classification is possible, the value UNKNOWN (or UNCLASSIFIED???) is assigned.")
   @appendable
   enum T_LaserDetectionClassificationType
   {
      L_LaserDetectionClassification__Invalid,
      @doc("The laser detection corresponds to a single pulse.")
      L_LaserDetectionClassification__Single_Pulse,
      @doc("The laser detection corresponds to a multiple pulse.")
      L_LaserDetectionClassification__Multiple_Pulse,
      @doc("The laser detection corresponds to a beam rider.")
      L_LaserDetectionClassification__Beam_Ride,
      @doc("The laser detection corresponds to a designator.")
      L_LaserDetectionClassification__Designator,
      @doc("The system has not been able to classify the detection.")
      L_LaserDetectionClassification__Unknown,
      @doc("The laser detection has not yet been classified.")
      L_LaserDetectionClassification__Initial
   };

   @doc("A list of laser detection classifiers.")
   typedef sequence <T_LaserDetectionClassificationType> T_ListOfDetectionClassificationType;

   @doc("All GVA Resources shall publish a common cesponse topic for each Domain Module they implement. Each Response message published shall use the same value for referenceNum as the Command message it is responding to.")
   @mutable
   struct C_Laser_Warning_System_CommandResponse
   {
      @doc("The resourceID of the LRU which will receive the sample.")
      @hashid @key P_GVA_Common_PSM::T_IdentifierType A_recipientID;
      @doc("The resourceID of the LRU which publishes this sample.")
      @hashid @key P_GVA_Common_PSM::T_IdentifierType A_sourceID;
      @doc("Identifies a sample published on a command topic. Each commanding resoure is responsible for ensuring that it stamps each sample it publishes on a particular Command Topic with a unique Reference Number (e.g. through an incrementing counter). When a commanded Resource publishes a sample on Command Response Topic, it must set the Reference Number to the same value as the Command to which it is responding.")
      @hashid P_LDM_Primitive_PSM::T_Int64 A_referenceNum;
      @doc("Specifies the metadata for this sample.")
      @hashid P_GVA_Common_PSM::T_MetadataType A_metadata;
      @doc("Enumerated type with several common error codes defined. If an operation fails, Resources shall use the value that most closely reflects the underlying reason for the failure")
      @hashid P_GVA_Common_PSM::T_ResponseCodeType A_responseCode;
      @doc("LRU-specific error code to be used if an LRU gives an error response not covered by the standard GVA error codes. In the special case where  ResponseCodeAttributeType is L_ResponseCodeType_Pending, this attribute shall be set to the the worst-case time to completion in milliseconds.")
      @hashid P_LDM_Primitive_PSM::T_Int32 A_additionalResponseCode;
   };

   @doc("This a specialisation of Laser_Detection. It is used solely to prevent the composition \"bearingDetectionLocation\" from crossing the domain boundary from Laser_Warning_System  to Tactical_Sensor. This is necessary because a composition crossing a domain boundary would introduce domain pollution as it would result in concepts from one domain being embedded into another domain.")
   @mutable
   struct C_Laser_Bearing_Detection_Location : P_Tactical_Sensor_PSM::C_Bearing_Detection_Location
   {
   };

   @doc("Defines, via a set of attributes and operations, the properties specific to (LWSs) Laser_Warning_Systemss (as specialisations of Tactical_Sensors).
       At any time, the LWS attribute values provide status information.")
   @mutable
   struct C_Laser_Warning_System : P_Tactical_Sensor_PSM::C_Tactical_Sensor
   {
      @hashid P_GVA_Common_PSM::T_IdentifierType A_laserWarningSystemCP_sourceID;
   };

   @doc("Defines, via a set of attributes, the properties common to all laser warning system types and their detections.")
   @mutable
   struct C_Laser_Warning_System_Specification : P_Tactical_Sensor_PSM::C_Tactical_Sensor_Specification
   {
      @doc("A list of enumerated values representing the types of laser detections supported by all Laser_Warning_Systems sharing this specification.
          Examples: SINGLE_PULSE, MULTIPLE_PULSE, DESIGNATOR")
      @hashid T_ListOfDetectionClassificationType A_supportedDetectionClassifications;
      @doc("A Boolean parameter which, when set to TRUE, indicates that all Laser_Warning_Systems sharing this specification support the ability to capture laser detection frequency.")
      @hashid P_LDM_Primitive_PSM::T_Boolean A_detectedFrequencySupported;
   };

   @doc("This required operation provides a placeholder for any behaviour that needs to be initiated in other domains when the specified object status changes.")
   @mutable
   struct C_Laser_Warning_System_CP_objectStatusChanged
   {
      @doc("The resourceID of the LRU which will receive the sample.")
      @hashid @key P_GVA_Common_PSM::T_IdentifierType A_recipientID;
      @doc("The resourceID of the LRU which publishes this sample.")
      @hashid @key P_GVA_Common_PSM::T_IdentifierType A_sourceID;
      @doc("Identifies a sample published on a command topic. Each commanding resoure is responsible for ensuring that it stamps each sample it publishes on a particular Command Topic with a unique Reference Number (e.g. through an incrementing counter). When a commanded Resource publishes a sample on Command Response Topic, it must set the Reference Number to the same value as the Command to which it is responding.")
      @hashid P_LDM_Primitive_PSM::T_Int64 A_referenceNum;
      @doc("Specifies the metadata for this sample.")
      @hashid P_GVA_Common_PSM::T_MetadataType A_metadata;
      @doc("Boolean indicating whether a response is required to this command. If TRUE, a response is not required. If FALSE, a response is required.")
      @hashid P_LDM_Primitive_PSM::T_Boolean A_responseNotRequired;
      @doc("A human readable identifier for the name of the Object. This shall be a text string in the following format as defined in the LDM Methodology and Modelling Standard:
          The uppercase labels that prefix each descriptor value are literal strings. Names in <angleBrackets> represent placeholders for actual values.
          OBJECT::<domainName>::<className>::<objectName>")
      @hashid P_LDM_Common_PSM::T_DescriptorType A_descriptor;
      @doc("Specifies the new status of the specified object.")
      @hashid P_LDM_Primitive_PSM::T_MediumString A_newStatus;
      @doc("Provides a generic means to convey relevant data items for use in the bridge method and/or the invoked provided operation(s).")
      @hashid P_LDM_Common_PSM::T_NameValuePairListType A_argumentList;
   };

   @doc("This required operation provides a placeholder for any behaviour that needs to be initiated in other domains when the specified object is deleted.")
   @mutable
   struct C_Laser_Warning_System_CP_objectDeleted
   {
      @doc("The resourceID of the LRU which will receive the sample.")
      @hashid @key P_GVA_Common_PSM::T_IdentifierType A_recipientID;
      @doc("The resourceID of the LRU which publishes this sample.")
      @hashid @key P_GVA_Common_PSM::T_IdentifierType A_sourceID;
      @doc("Identifies a sample published on a command topic. Each commanding resoure is responsible for ensuring that it stamps each sample it publishes on a particular Command Topic with a unique Reference Number (e.g. through an incrementing counter). When a commanded Resource publishes a sample on Command Response Topic, it must set the Reference Number to the same value as the Command to which it is responding.")
      @hashid P_LDM_Primitive_PSM::T_Int64 A_referenceNum;
      @doc("Specifies the metadata for this sample.")
      @hashid P_GVA_Common_PSM::T_MetadataType A_metadata;
      @doc("Boolean indicating whether a response is required to this command. If TRUE, a response is not required. If FALSE, a response is required.")
      @hashid P_LDM_Primitive_PSM::T_Boolean A_responseNotRequired;
      @doc("A human readable identifier for the name of the Object. This shall be a text string in the following format as defined in the LDM Methodology and Modelling Standard:
          The uppercase labels that prefix each descriptor value are literal strings. Names in <angleBrackets> represent placeholders for actual values.
          OBJECT::<domainName>::<className>::<objectName>")
      @hashid P_LDM_Common_PSM::T_DescriptorType A_descriptor;
   };

   @doc("This required operation provides a placeholder for any behaviour that needs to be initiated in other domains when the specified object is created.")
   @mutable
   struct C_Laser_Warning_System_CP_objectCreated
   {
      @doc("The resourceID of the LRU which will receive the sample.")
      @hashid @key P_GVA_Common_PSM::T_IdentifierType A_recipientID;
      @doc("The resourceID of the LRU which publishes this sample.")
      @hashid @key P_GVA_Common_PSM::T_IdentifierType A_sourceID;
      @doc("Identifies a sample published on a command topic. Each commanding resoure is responsible for ensuring that it stamps each sample it publishes on a particular Command Topic with a unique Reference Number (e.g. through an incrementing counter). When a commanded Resource publishes a sample on Command Response Topic, it must set the Reference Number to the same value as the Command to which it is responding.")
      @hashid P_LDM_Primitive_PSM::T_Int64 A_referenceNum;
      @doc("Specifies the metadata for this sample.")
      @hashid P_GVA_Common_PSM::T_MetadataType A_metadata;
      @doc("Boolean indicating whether a response is required to this command. If TRUE, a response is not required. If FALSE, a response is required.")
      @hashid P_LDM_Primitive_PSM::T_Boolean A_responseNotRequired;
      @doc("A human readable identifier for the name of the Object. This shall be a text string in the following format as defined in the LDM Methodology and Modelling Standard:
          The uppercase labels that prefix each descriptor value are literal strings. Names in <angleBrackets> represent placeholders for actual values.
          OBJECT::<domainName>::<className>::<objectName>")
      @hashid P_LDM_Common_PSM::T_DescriptorType A_descriptor;
   };

   @doc("Placeholder for counterpart associations and services in build sets.")
   @mutable
   struct C_Laser_Warning_System_CP
   {
      @doc("The resourceID of the LRU which publishes this sample.")
      @hashid @key P_GVA_Common_PSM::T_IdentifierType A_sourceID;
      @doc("Specifies the metadata for this sample.")
      @hashid P_GVA_Common_PSM::T_MetadataType A_metadata;
      @hashid P_GVA_Common_PSM::T_IdentifierType A_cpLaserWarningSystem_sourceID;
   };

   @doc("The properties common to all laser detections.
       Note: An instance of a Laser_Detection is created for each detection produced by the receiver. The laser warning system is thereafter responsible for deleting the laser detection when no longer active.")
   @mutable
   struct C_Laser_Detection : P_Tactical_Sensor_PSM::C_Detection
   {
      @doc("Specifies the finalised classification of the laser detection. The classification is valid only when
          a) the \"finalised\" attribute is set to TRUE, AND
          b) the classification is supported by the corresponding Laser_Warning_System type.
          Sample classifications: MULTIPLE_PULSE, DESIGNATOR, BEAM_RIDER
          Note: When classification has not been possible, the attribute shall be assigned the value UNKNOWN.")
      @hashid T_LaserDetectionClassificationType A_detectionClassification;
      @doc("A Boolean parameter which, when set to TRUE, indicates that the classification of the laser detection is finalised.")
      @hashid P_LDM_Primitive_PSM::T_Boolean A_finalised;
      @doc("Represents the time stamped occurrence of a classified laser detection.")
      @hashid P_LDM_Common_PSM::T_DateTimeType A_detectionOccurred;
      @doc("When the Laser_Warning_System supports frequency detection, the value in Hertz is captured here.")
      @hashid @optional P_LDM_Common_PSM::T_FrequencyInHertzType A_detectedFrequency;
      @doc("current state of the detection. See type description for a description of the states.")
      @hashid T_Laser_Detection_StateType A_currentState;
      @hashid sequence <C_Laser_Bearing_Detection_Location> A_bearingDetectionLocations;
   };
};

#endif
