#ifndef LDM_PRIMITIVE_PSM__IDL
#define LDM_PRIMITIVE_PSM__IDL

@doc("Contains primitive (bottom-level) data types.")
module P_LDM_Primitive_PSM
{
   @doc("A single character")
   typedef char T_Char;

   @doc("A string of less than 20 characters in length.")
   typedef sequence <T_Char, 20> T_ShortString;

   @doc("A string of less than 500 characters in length.")
   typedef sequence <T_Char, 500> T_LongString;

   @doc("A 16 Bit signed Integer")
   typedef short T_Int16;

   @doc("A 32 bit signed Integer")
   typedef long T_Int32;

   @doc("A 64 bit signed Integer")
   typedef long long T_Int64;

   @doc("A boolean")
   typedef boolean T_Boolean;

   @doc("A double-precision floating-point value")
   typedef double T_Double;

   @doc("A string of less than 100 characters in length.")
   typedef sequence <T_Char, 100> T_MediumString;

   @doc("An undounded string")
   typedef string T_String;
};

#endif
